package com.company;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Objects;

public class User implements ClassesToStoreInFiles{
    private String userType;
    private String name;
    private String CPR;
    private String password;

    public User(String userType, String name, String CPR, String password){
        this.userType = userType;
        this.name = name;
        this.CPR = CPR;
        this.password = password;
        writeToFile();
    }

    public User(String userType, String name, String CPR, String password, boolean readFromFile){
        this.userType = userType;
        this.name = name;
        this.CPR = CPR;
        this.password = password;
    }

    public boolean login(String password){
        return password.equals(this.password);
    }

    public String getCPR() {
        return CPR;
    }
    

    public String getName() {
        return name;
    }

    public void setId(String id) {
        this.CPR = id;
    }

    //.equals is auto-generated by IntelliJ, might need to be changed later.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return CPR.equals(user.CPR);
    }

    @Override
    public int hashCode() {
        return Objects.hash(CPR);
    }

    @Override
    public void writeToFile(){
    String StringToFile = this.userType + "," + this.name + "," + this.CPR + "," + this.password + "\n";
        try {
            FileWriter Userfw = new FileWriter("src/resourser/EmployeeListFile", true);
            Userfw.write(StringToFile);
            Userfw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    public String toString() {
        return "User{" +
                "name='" + name + '\'' +
                ", CPR='" + CPR + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
